### ISSUE TITLE
Please use thread pool

### ISSUE THREAD

**Issue by vitalk** [MaximPodrez/LeverX_Task_3#2]
https://github.com/MaximPodrez/LeverX_Task_3/blob/b5ffcd4be46a541e6685f579e5adda37e81ce6fb/main.py#L16

**Comment by MaximPodrez** [comment]
Done.

Changed on this:

num_processes = 5
    with ThreadPool(processes=num_processes) as pool:
        a = sum(pool.map(function, generator(num_processes)))
